services:
  custom-load-balancer:
    build:
      context: .
      dockerfile: docker/Dockerfile.loadbalancer
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/usr/local/bin/config.yml
    depends_on:
      - server
    networks:
      - lb-network

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    command: ["--latency", "-1s"] # config.yaml preferred
    environment:
      - PORT=9090
    labels:
      - "server=true"
    networks:
      - lb-network
networks:
  lb-network:
    driver: bridge
