health_check:
  interval: 5s
  timeout: 5s

load_balancer:
  algorithm: "Random" 

servers:
  - url: "http://server1:8081"
  - url: "http://server2:8082" 
  - url: "http://server3:8083"

metrics:
  enabled: false