health_check:
  interval: 5s
  timeout: 5s

load_balancer:
  algorithm: "RoundRobin" 

servers:
  - url: "http://server:8080"
    count: 5
    weight: 1
    artificial_latency: -1ms

metrics:
  enabled: true
  latency_samples: 100