health_check:
  interval: 5s
  timeout: 5s

load_balancer:
  algorithm: "RoundRobin" 

servers:
  - url: "http://server1:8081"
    weight: 1
    artificial_latency: -1ms
  - url: "http://server2:8082" 
    weight: 1
    artificial_latency: -1ms
  - url: "http://server3:8083"
    weight: 1
    artificial_latency: -1ms

metrics:
  enabled: true
  latency_samples: 100