name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24.4"
    - name: Run unit tests
      run: |
        go test ./internal/...
    - name: Run Docker compose
      run: |
        docker compose up -d  # Run containers in background
    - name: Run integration tests
      run: |
        go test ./integration/...
    - name: Stop Docker compose
      if: always()  # Always run even if integration tests fail
      run: |
        docker compose down

